-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- USERS (Motoristas, Admins, Visualizadores)
create table if not exists public.app_users (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null default auth.uid(),
    nome text not null,
    role text not null check (role in ('admin', 'motorista', 'visualizador')),
    "truckId" bigint, -- Reference to trucks table (can be null)
    "salarioFixo" numeric,
    "comKmCarregado" numeric,
    "comKmVazio" numeric,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.app_users enable row level security;
create policy "Users can CRUD their own data" on public.app_users for all using (auth.uid() = user_id);

-- TRUCKS
create table if not exists public.trucks (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null default auth.uid(),
    placa text not null,
    modelo text,
    ano integer,
    cor text,
    status text default 'disponivel',
    "kmAtual" integer default 0,
    "kmCarregado" numeric, -- Custom rate per truck
    "kmVazio" numeric,     -- Custom rate per truck
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.trucks enable row level security;
create policy "Users can CRUD their own data" on public.trucks for all using (auth.uid() = user_id);

-- FUELINGS (Abastecimentos)
create table if not exists public.fuelings (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null default auth.uid(),
    "truckId" bigint not null,
    data date not null,
    km integer not null,
    litros numeric not null,
    "valorTotal" numeric not null,
    posto text,
    "tipoCombustivel" text,
    local text,
    "mediaParcial" numeric,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.fuelings enable row level security;
create policy "Users can CRUD their own data" on public.fuelings for all using (auth.uid() = user_id);

-- FREIGHTS (Fretes)
create table if not exists public.freights (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null default auth.uid(),
    "truckId" bigint not null,
    data date not null,
    cliente text not null,
    origem text not null,
    destino text not null,
    produto text,
    peso numeric,
    "valorFrete" numeric not null,
    km integer not null,
    tipo text check (tipo in ('carregado', 'vazio')),
    modalidade text default 'km', -- 'km' or 'fechado'
    "comissaoFechado" numeric, -- Value for driver commission if modalidade='fechado'
    status text default 'pendente',
    observacoes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.freights enable row level security;
create policy "Users can CRUD their own data" on public.freights for all using (auth.uid() = user_id);

-- FINES (Multas)
create table if not exists public.fines (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null default auth.uid(),
    "truckId" bigint not null,
    data date not null,
    valor numeric not null,
    motivo text,
    loca text,
    pontos integer,
    status text default 'pendente',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.fines enable row level security;
create policy "Users can CRUD their own data" on public.fines for all using (auth.uid() = user_id);

-- TRUCK EXPENSES (Despesas do Caminhão)
create table if not exists public.truck_expenses (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null default auth.uid(),
    "truckId" bigint not null,
    data date not null,
    tipo text not null, -- Manutencao, Seguro, Pneu, etc
    valor numeric not null,
    descricao text,
    fornecedor text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.truck_expenses enable row level security;
create policy "Users can CRUD their own data" on public.truck_expenses for all using (auth.uid() = user_id);

-- DRIVER EXPENSES (Reembolsos)
create table if not exists public.driver_expenses (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null default auth.uid(),
    "userId" bigint not null, -- Refers to app_users.id (the driver)
    data date not null,
    tipo text not null,
    valor numeric not null,
    descricao text,
    comprovante text, -- URL or base64 (avoid storing large base64 here if possible)
    status text default 'aprovado',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.driver_expenses enable row level security;
create policy "Users can CRUD their own data" on public.driver_expenses for all using (auth.uid() = user_id);

-- DRIVER BONUSES
create table if not exists public.driver_bonuses (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null default auth.uid(),
    "userId" bigint not null,
    data date not null,
    valor numeric not null,
    motivo text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.driver_bonuses enable row level security;
create policy "Users can CRUD their own data" on public.driver_bonuses for all using (auth.uid() = user_id);

-- DRIVER DISCOUNTS (Vales)
create table if not exists public.driver_discounts (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null default auth.uid(),
    "userId" bigint not null,
    data date not null,
    valor numeric not null,
    motivo text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.driver_discounts enable row level security;
create policy "Users can CRUD their own data" on public.driver_discounts for all using (auth.uid() = user_id);

-- CLOSINGS (Fechamento Mensal - Cache)
create table if not exists public.closings (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null default auth.uid(),
    "truckId" bigint not null,
    mes integer not null,
    ano integer not null,
    "totalAbastecimento" numeric,
    "totalFretes" numeric,
    "totalMultas" numeric,
    "totalDespesas" numeric,
    "totalLitros" numeric,
    "totalKm" numeric,
    "mediaConsumo" numeric,
    saldo numeric,
    data_geracao timestamp with time zone default timezone('utc'::text, now()),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.closings enable row level security;
create policy "Users can CRUD their own data" on public.closings for all using (auth.uid() = user_id);

-- SETTINGS (Key-Value)
create table if not exists public.settings (
    key text primary key,
    user_id uuid references auth.users not null default auth.uid(),
    value jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.settings enable row level security;
create policy "Users can CRUD their own data" on public.settings for all using (auth.uid() = user_id);
