-- Migration: Driver Closings (Fechamentos do Motorista Salvos)
-- Run this in the Supabase SQL Editor

create table if not exists public.driver_closings (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null default auth.uid(),
    "driverId" bigint not null,
    "truckId" bigint,
    "driverName" text,
    "dataInicio" date not null,
    "dataFim" date not null,
    "salarioFixo" numeric default 0,
    "salarioFixoBase" numeric default 0,
    "diasTrabalhados" integer default 0,
    "diasNoMes" integer default 0,
    "totalComissaoKm" numeric default 0,
    "totalComissaoFechado" numeric default 0,
    "premioMedia" numeric default 0,
    "totalExpenses" numeric default 0,
    "totalBonuses" numeric default 0,
    "totalDiscounts" numeric default 0,
    "totalPagar" numeric default 0,
    "totalSemVales" numeric default 0,
    "geradoEm" text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.driver_closings enable row level security;
create policy "Users can CRUD their own data" on public.driver_closings
    for all using (auth.uid() = user_id);
